name: Update translations

on:
  schedule:
    - cron: '0 8 * * 1'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y csvkit translate-toolkit dos2unix

      - name: Configure Git
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "Automated GitHub Action"

      - name: Run generate.sh in each directory and commit changes
        run: |
          for d in */; do
            if [ -f "${d}generate.sh" ]; then
              echo "Running generate.sh in $d"
              if "${d}generate.sh"; then
                git add "$d"
                if ! git diff --quiet --cached; then
                  git pull --rebase
                  git commit -m "Update files in $d via GitHub Actions"
                  git push origin HEAD
                else
                  echo "No changes in $d"
                fi
              else
                echo "generate.sh failed in $d, skipping..."
              fi
            fi
          done
