name: Update translations

on:
  schedule:
    - cron: '0 8 * * 1'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y csvkit translate-toolkit dos2unix

      - name: Configure Git
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "Automated GitHub Action"

      - name: Run generate.sh in each directory and commit changes
        run: |
          allowed_to_fail=("sumatra/")
          for d in */; do
            if [ -f "${d}generate.sh" ]; then
              echo "Running generate.sh in $d"
              if "${d}generate.sh"; then
                if git diff --unified=0 "$d" | grep "^-\|^\+" | grep -v "^---" | grep -v "^+++" | grep -v "POT-Creation-Date"; then
                  git add "$d"
                  git commit -m "Update files in $d via GitHub Actions"
                  git push origin HEAD
                else
                  echo "No significant changes in $d"
                  git checkout "$d"
                fi
              else
                echo "generate.sh failed in $d"
                if [[ " ${allowed_to_fail[@]} " =~ " ${d} " ]]; then
                  echo "$d failed but is whitelisted, continuing..."
                else
                  echo "Stopping execution due to failure in $d"
                  exit 1
                fi
                git checkout "$d"
              fi
              git clean -f
            fi
          done
